# Generated by Django 3.1.6 on 2021-04-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]
    
    run_before = [
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
    ]
